blank_issues_enabled: false
contact_links:
  - name: Bug Report Guidelines
    url: https://github.com/Slimefun/Slimefun4/wiki/How-to-report-bugs
    about: Guidelines on how to make good Bug reports
  - name: Discord Server (for Questions and Suggestions)
    url: https://discord.gg/slimefun
    about: "Please ask and answer questions here, in the #other-addons channel."
